name: NS-3 Docker Simulation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  simulate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: p2pool-ns3:latest
    
    - name: Run simulation
      run: |
        docker run --rm \
          -v $(pwd)/results:/results \
          p2pool-ns3:latest \
          --nNodes=50 \
          --simDuration=600 \
          --RngRun=1 > results/simulation-output.txt
    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: simulation-results
        path: results/simulation-output.txt
